export const GET_LIST_QUESTION_REQUEST = "question/GET_LIST_QUESTION_REQUEST";
export const GET_LIST_QUESTION_SUCCESS = "question/GET_LIST_QUESTION_SUCCESS";
export const GET_LIST_QUESTION_FAILED = "question/GET_LIST_QUESTION_FAILED";
