export const GET_LESSON_PAGING_REQUEST = "lesson/GET_LESSON_PAGING_REQUEST";
export const GET_LESSON_PAGING_SUCCESS = "lesson/GET_LESSON_PAGING_SUCCESS";
export const GET_LESSON_PAGING_FAILED = "lesson/GET_LESSON_PAGING_FAILED";
