export const GET_COURSE_PAGING_REQUEST = "course/GET_COURSE_PAGING_REQUEST";
export const GET_COURSE_PAGING_SUCCESS = "course/GET_COURSE_PAGING_SUCCESS";
export const GET_COURSE_PAGING_FAILED = "course/GET_COURSE_PAGING_FAILED";
