export const GET_LIST_TOPIC_REQUEST = "topic/GET_LIST_TOPIC_REQUEST";
export const GET_LIST_TOPIC_SUCCESS = "topic/GET_LIST_TOPIC_SUCCESS";
export const GET_LIST_TOPIC_FAILED = "topic/GET_LIST_TOPIC_FAILED";
