export const GET_LIST_NOTIFY_REQUEST = "notify/GET_LIST_NOTIFY_REQUEST";
export const GET_LIST_NOTIFY_SUCCESS = "notify/GET_LIST_NOTIFY_SUCCESS";
export const GET_LIST_NOTIFY_FAILED = "notify/GET_LIST_NOTIFY_FAILED";
