export const GET_TOPIC_LIST_REQUEST = "topic/GET_TOPIC_LIST_REQUEST";
export const GET_TOPIC_LIST_SUCCESS = "topic/GET_TOPIC_LIST_SUCCESS";
export const GET_TOPIC_LIST_FAILED = "topic/GET_TOPIC_LIST_FAILED";
