export const GET_USER_PAGING_REQUEST = "user/GET_USER_PAGING_REQUEST";
export const GET_USER_PAGING_SUCCESS = "user/GET_USER_PAGING_SUCCESS";
export const GET_USER_PAGING_FAILED = "user/GET_USER_PAGING_FAILED";
