export const GET_COURSE_LIST_REQUEST = "course/GET_COURSE_LIST_REQUEST";
export const GET_COURSE_LIST_SUCCESS = "course/GET_COURSE_LIST_SUCCESS";
export const GET_COURSE_LIST_FAILED = "course/GET_COURSE_LIST_FAILED";
